create table if not exists books (
    id bigint generated by default as identity primary key,
    book_id text unique not null,
    title text not null,
    author text not null,
    isbn text not null,
    quantity integer not null default 0,
    borrowed_time timestamptz,
    return_time timestamptz
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password text not null
);

create table if not exists admins (
    id bigint generated by default as identity primary key,
    admin_username text unique not null,
    admin_password text not null
);
